services:
  postgres:
    build: containers/postgres
    container_name: work-in-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workin
  test-app:
    image: descenty/work_in_spring:latest
    container_name: work-in-test-app
    command: ./gradlew test
    restart: always
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: workin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
