services:
  postgres:
    image: postgres:latest
    container_name: work-in-postgres
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workin
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: