spring:
  web:
    cors:
      allowed-origins: "http://localhost:19006"
  datasource:
    url: jdbc:postgresql://${DB_HOST}/workin
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
  data:
    rest:
      basePath: /api
