### Get all areas
GET http://localhost:8080/api/v1/areas

> {%
    client.test("Status code is 200", function() {
        client.assert(response.status === 200);
        // check that response body is a list
        client.assert(response.body instanceof Array);
    });
%}

### Add area
POST {{BASE_URL}}/areas
Content-Type: application/json

{
  "name": "Moscow"
}

> {%
    client.test("Status code is 201", function() {
        client.assert(response.status === 201);
    });
%}

### Get area by id
GET {{BASE_URL}}/areas/122

#
#
#
#- /areas/{id} - get area by id
#- /areas/{id}/vacancies - get all vacancies in area
#- /areas/{id}/companies - get all companies in area
#- /areas/{id}/companies/{id} - get company by id in area
#- /areas/{id}/companies/{id}/vacancies - get all vacancies in company in area
#- /areas/{id}/companies/{id}/vacancies/{id} - get vacancy by id in company in area
#
#
#/areas/122/vacancies/${UUID}
#/users/${UUID}
#/areas/122/companies/d5b1e6e0-7b28-11e9-8f9e-2a86e4085a59/vacancies/${UUID}
